### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by wxh06** [0f-0b/luogu-api-docs#14]
能否将该仓库作为包发布至 npm registry？

现在仓库根目录不存在 package.json，使用 [pnpm](https://pnpm.io/zh/) 甚至无法将 `github:0f-0b/luogu-api-docs` 添加为依赖项。

**Comment by 0f-0b** [comment]
在 7ec85d2052c6080dafaa061589807df3b8c9f9ce 增加了开源协议。如果需要用到这个项目里的内容那么直接复制就好了。

**Comment by wxh06** [comment]
主要目的是方便安装和管理更新。现在我自己是采取 git submodule 的方案，略显麻烦。

**Comment by 0f-0b** [comment]
在 `preinstall` 脚本里运行 `git submodule update --init`，需要更新时运行 `git submodule update --remote`，这样可以满足需求吗？

**Comment by wxh06** [comment]
经过尝试，现在 pnpm 可以将本 GitHub 仓库（没有 `package.json`）作为依赖安装了。
