### ISSUE TITLE
请问如何通过_uid和__client_id获取CSRF口令？

### ISSUE THREAD

**Issue by g1thubhack3r** [0f-0b/luogu-api-docs#27]
rt
翻了半天浏览器开发人员工具的网络栏愣是没找到用来获取CSRF口令的请求

**Comment by 0f-0b** [comment]
CSRF 令牌是嵌入在网页 HTML 中的。带上 cookie 请求任何页面（如首页 `/`），在返回的 HTML 里找到 `name` 属性值为 `csrf-token` 的 `meta` 元素，其 `content` 属性的值就是 CSRF 令牌。[相关文档](https://0f-0b.github.io/luogu-api-docs/misc#%E8%8E%B7%E5%8F%96-csrf-%E4%BB%A4%E7%89%8C)。

**Comment by g1thubhack3r** [comment]
OK，谢谢！
~~眼瞎了请求标头都看了就是没看响应~~
