### ISSUE TITLE
Update artictle api

### ISSUE THREAD

**Issue by Mr-Python-in-China** [0f-0b/luogu-api-docs#28]
洛谷更新了新的专栏功能 需要更新api

**Comment by Mr-Python-in-China** [comment]
好像好多api都换成x-lentille-request请求头的那种了 是不是也要更

**Comment by 0f-0b** [comment]
0ab79141941d77af48979f7cb9beee063542410b 中更新了 `/article/mine`。

**Comment by Mr-Python-in-China** [comment]
edit也更新了吧

**Comment by Mr-Python-in-China** [comment]
你要不把整个专栏部分检查一下）

**Comment by 0f-0b** [comment]
`/article/:lid/edit` 返回的信息比起 `/article/:lid` 只多个 `isAdmin` 表示当前用户是否有专栏管理权限，看起来没什么用所以没有收录。

**Comment by Mr-Python-in-China** [comment]
明白了
