### ISSUE TITLE
新字段 管理组提示

### ISSUE THREAD

**Issue by Mr-Python-in-China** [0f-0b/luogu-api-docs#34]
E.g. <https://www.luogu.com.cn/article/6k8028ou>
![image](https://github.com/user-attachments/assets/98d3282a-520e-4687-bdce-f533c67b2ea8)

```typescript
adminNote: string | null;
```

**Comment by 0f-0b** [comment]
已经添加。

<https://github.com/0f-0b/luogu-api-docs/blob/c3338d54763376549dee39eda53421b333ba642a/luogu-api.d.ts#L1108>
